### ISSUE TITLE
从省进入市乱码问题

### ISSUE THREAD

**Issue by yixingruohuo** [oliverdai/echarts#1]
从省进入市，市的地图无法更改颜色，值域，疑似值域出现乱码，另，导入的市的json文件有乱码怎么修改，谢谢

**Comment by oliverdai** [comment]
颜色、值域是根据设置来的，市的有数据设置值就会有颜色，值域乱码建议看一下官方api，另地图json已经不能下载了，json文件乱码建议重新网上找找。
